# Generated by Django 5.0.7 on 2024-07-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sequence',
            field=models.IntegerField(),
        ),
    ]
