# Generated by Django 5.0.7 on 2024-07-16 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_request', '0002_sendingrequest'),
        ('weight_range', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingrequest',
            name='range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weight_range.weight_range'),
        ),
    ]
