# Generated by Django 5.0.7 on 2024-07-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_request', '0004_sendingrequest_reference_alter_sendingrequest_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingrequest',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sendingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='pending', max_length=50),
        ),
    ]
