# Generated by Django 5.0.7 on 2024-07-17 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_request', '0005_sendingrequest_delivery_time_sendingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
