# Generated by Django 5.0.7 on 2024-07-18 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send_request', '0006_sendingrequest_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('reference', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('client', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('agent', models.CharField(max_length=255)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='send_request.sendingrequest')),
            ],
        ),
    ]
